### ISSUE TITLE
Protect certificates used for OB-UI-e2e test

### ISSUE THREAD

**Issue by jsanhc** [OpenBankingToolkit/openbanking-toolkit#54]
### Story
As a developer I want to have protected the certificates used in the tests projects So that no one can use then for other or bad purposes.

### Tasks
- [x] Define a solution to move the certificates to protected place to use then only in the tests projects and nobody can get them and use them for a different purpose.

### Projects affected
- [x] [ob-ui-e2e](https://github.com/ForgeCloud/ob-ui-e2e)

**Comment by jsanhc** [comment]
## Solution for ob-ui-e2e
### Configuration
Added the proper configuration in cypress.json configuration file to support client certificates:
```json
"clientCertificates": [
    {
      "url": "https://*.*.forgerock.financial",
      "ca": [],
      "certs": [
        {
          "cert": "client/certs/OBWac.pem",
          "key": "client/certs/OBWac.key"
        }
      ]
    }
  ]
```
### Run the tests
**From a pipeline**
Create new shared secret in codefresh with the certificates in base64 and use them in the pipeline:
```yaml
run_e2e_ui-tests:
        title: 'UI e2e tests'
        image: cypress/included:9.5.4
        working_directory: ${{ob_ui_e2e_clone}}
        commands:
          - mkdir -p client/certs
          - echo "$OB_WAC_PEM_B64" | base64 -d > client/certs/OBWac.pem
          - echo "$OB_WAC_KEY_B64" | base64 -d > client/certs/OBWac.key
          - npm ci
          - cypress run --env configFile=${{CLUSTER_NAME}}
```
**In local**
The developer will need to get the certificates and set them in the proper folder, See [Readme file](https://github.com/ForgeCloud/ob-ui-e2e)
